name: Testing

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:testing
  PROJECT_PATH: /opt/04-nike-testing/user-service

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.4.0
      with:
        mongodb-version: 4.4
        mongodb-port: 27011

    - run: npm ci
    - run: npm test
    env:
      CI: true
  
  build:
    name: 'Build docker image'
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile.prod
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  
  deploy:
    name: 'Update testing server'
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    - name: SSH and deploy in server
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        PORT: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.PROJECT_PATH }}
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}-temp
          docker rmi ${{ env.IMAGE_NAME }}
          docker pull ${{ env.IMAGE_NAME }}
          docker rmi ${{ env.IMAGE_NAME }}-temp
          echo IMAGE=${{ env.IMAGE_NAME }} > .env
          docker-compose up -d